// Code generated by MockGen. DO NOT EDIT.
// Source: tstorage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTstorageService is a mock of TstorageService interface.
type MockTstorageService struct {
	ctrl     *gomock.Controller
	recorder *MockTstorageServiceMockRecorder
}

// MockTstorageServiceMockRecorder is the mock recorder for MockTstorageService.
type MockTstorageServiceMockRecorder struct {
	mock *MockTstorageService
}

// NewMockTstorageService creates a new mock instance.
func NewMockTstorageService(ctrl *gomock.Controller) *MockTstorageService {
	mock := &MockTstorageService{ctrl: ctrl}
	mock.recorder = &MockTstorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTstorageService) EXPECT() *MockTstorageServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTstorageService) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTstorageServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTstorageService)(nil).Close))
}
