basePath: /apis
definitions:
  ResponseError:
    properties:
      message:
        type: string
    type: object
  ResponseOk:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /version:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseOk'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseError'
      summary: Get version of cray-nls service
      tags:
      - Misc
swagger: "2.0"
